# Generated by Django 3.2.6 on 2021-08-27 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('idno', models.IntegerField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('m1', models.IntegerField(max_length=1000)),
                ('m2', models.IntegerField(max_length=1000)),
                ('m3', models.IntegerField(max_length=1000)),
                ('average', models.FloatField()),
                ('grade', models.CharField(max_length=10)),
            ],
        ),
    ]
